services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=staging
    env_file:
      - .env.${DOCKER_ENV:-staging}
    volumes:
      - ./data:/app/data
    networks:
      - app-network
    depends_on:
      - pdf-service
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 3s
      retries: 3

  pdf-service:
    build:
      context: ./lib/image
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - .env.${DOCKER_ENV:-staging}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://pdf-service:8082/health"]
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  data:
