name: Go Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENV: test
      SESSION_SECRET_KEY: "5j4b0nRGun6btLF3MC+hq9Hq+JhUV5NVSjhHO5RTY8o="
      TEST_SESSION_SECRET_KEY: "5j4b0nRGun6btLF3MC+hq9Hq+JhUV5NVSjhHO5RTY8o="

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run tests
      run: go test ./... -v
    
    - name: Run tests with coverage
      run: go test ./... -coverprofile=coverage.out
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.out
        fail_ci_if_error: false
